### ISSUE TITLE
It doesn't work with 1.19.2. Will it possible to update? Thanks :D

### ISSUE THREAD

**Issue by Aitooor** [StrangeOne101/RealBiomeCondition#6]
[01:02:48 ERROR]: Could not pass event MythicConditionLoadEvent to RealBiomeConditon v1.0.3
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_18_R2/CraftServer
at com.strangeone101.realbiomecondition.NMSUtils.biomeRegistry(NMSUtils.java:23) ~[RealBiomeCondition-1.0.4.jar:?]
at com.strangeone101.realbiomecondition.BiomeReader.getBiomeMap(BiomeReader.java:23) ~[RealBiomeCondition-1.0.4.jar:?]
at com.strangeone101.realbiomecondition.conditions.RealBiomeCondition.lambda$new$0(RealBiomeCondition.java:33) ~[RealBiomeCondition-1.0.4.jar:?]
at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
at com.strangeone101.realbiomecondition.conditions.RealBiomeCondition.(RealBiomeCondition.java:32) ~[RealBiomeCondition-1.0.4.jar:?]
at com.strangeone101.realbiomecondition.Plugin.onCustomConditionLoad(Plugin.java:32) ~[RealBiomeCondition-1.0.4.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor503.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:git-Pufferfish-42]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at io.lumine.mythic.core.skills.conditions.CustomCondition.lambda$new$0(CustomCondition.java:34) ~[MythicMobs-5.1.4.jar:?]
at io.lumine.mythic.bukkit.utils.Delegates$RunnableToSupplier.get(Delegates.java:121) ~[MythicMobs-5.1.4.jar:?]
at io.lumine.mythic.bukkit.utils.promise.LuminePromise$SupplyRunnable.run(LuminePromise.java:654) ~[MythicMobs-5.1.4.jar:?]
at io.lumine.mythic.bukkit.utils.tasks.LumineExecutors$SchedulerWrappedRunnable.run(LumineExecutors.java:70) ~[MythicMobs-5.1.4.jar:?]
at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[pufferfish-1.19.2.jar:git-Pufferfish-42]
at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[pufferfish-1.19.2.jar:git-Pufferfish-42]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1475) ~[pufferfish-1.19.2.jar:git-Pufferfish-42]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:449) ~[pufferfish-1.19.2.jar:git-Pufferfish-42]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1399) ~[pufferfish-1.19.2.jar:git-Pufferfish-42]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[pufferfish-1.19.2.jar:git-Pufferfish-42]
at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[pufferfish-1.19.2.jar:git-Pufferfish-42]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_18_R2.CraftServer
... 23 more

**Comment by Aitooor** [comment]
Sorry for opening a Pull Request, i close inmediatly
